experiment_key_column:
    description: 'Column used to group samples to make pseudobulk.'
    value: 'experiment_id'
anndata_cell_label:
    description: 'Anndata cell label column in obs slot.'
    value: 'cluster'
differential_expression:
    run_process: true
    models:
        description: 'List of differential formula and params.
            All covariates in formula should be listed in either
                variable_continuous or variable_discrete.'
        mean_cp10k_filter: 1
        value:
            - method: ''
              formula: '~ '
              variable_target: ''
              variable_continuous: ''
              variable_discrete: ''
              variable_discrete_level: ''
              pre_filter_genes: true
              proportion_covariate_column: 'cluster'
              include_proportion_covariates: true
            - method: ''
              formula: '~ '
              variable_target: ''
              variable_continuous: ''
              variable_discrete: ''
              variable_discrete_level: ''
              pre_filter_genes: false
              proportion_covariate_column: 'cluster'
              include_proportion_covariates: true
            - method: ''
              formula: '~ '
              variable_target: ''
              variable_continuous: ''
              variable_discrete: ''
              variable_discrete_level: ''
              pre_filter_genes: true
              proportion_covariate_column: 'cluster'
              include_proportion_covariates: false
    de_merge_config:
        ihw_correction:
            run_process: false
            description: 'Run IHW to correct differential expression results.'
            value:
                covariates: ''
                alpha: 0.1
    de_plot_config:
        mean_expression_filter:
            description: 'For comparison plots, drop genes whose mean
                expression for a group in anndata_cell_label is < this value.
                Example: if gene A expression is 0 counts in cluster 1 and 10
                in cluster 2, it will be dropped from cluster 1 but not cluster
                2.'
            value:
                - 0.0
                - 0.25
    gsea_config:
        run_process: true
        description: 'Parameters to run fGSEA.'
        sample_size: 101
        score_type: 'std'
        fgsea_parameters:
            - min_set_size: 1
              max_set_size: Inf
              eps: 0
              database: 'c2.cp.reactome,c2.cp.kegg,c5.bp,c5.cc,c5.mf'
        gsea_summarize_parameters:
            - distance_metric: 'kappa'
              clustering_method: 'louvain'
